/* AI HQ V9 — Production Gateway */
(() => {
  const V9_VERSION = '9.2.1';

  function ensureV9() {
    state.v9 = state.v9 || {};
    state.v9.settings = {
      gatewayUrl: state.v9.settings?.gatewayUrl || state.v8?.settings?.gatewayUrl || 'https://ai-hq-gateway.vercel.app',
      pollMs: 1200,
      maxPolls: 90,
      ...state.v9.settings
    };
    state.v9.health = state.v9.health || null;
    state.v9.approvals = Array.isArray(state.v9.approvals) ? state.v9.approvals : [];
    state.v8 = state.v8 || { jobs: [], artifacts: [], logs: [], settings: {} };
    state.v8.jobs = Array.isArray(state.v8.jobs) ? state.v8.jobs : [];
    state.v8.artifacts = Array.isArray(state.v8.artifacts) ? state.v8.artifacts : [];
    state.v8.logs = Array.isArray(state.v8.logs) ? state.v8.logs : [];
    save();
  }

  function token() {
    try { return sessionStorage.getItem('aihq_v9_gateway_token') || sessionStorage.getItem('aihq_v8_gateway_token') || ''; }
    catch { return ''; }
  }

  function setToken(value) {
    try {
      if (value) {
        sessionStorage.setItem('aihq_v9_gateway_token', value);
        sessionStorage.setItem('aihq_v8_gateway_token', value);
      } else {
        sessionStorage.removeItem('aihq_v9_gateway_token');
        sessionStorage.removeItem('aihq_v8_gateway_token');
      }
    } catch {}
  }

  function baseUrl() {
    return String(state.v9.settings.gatewayUrl || '').trim().replace(/\/$/, '');
  }

  function v9Log(action, details = '', jobId = '', level = 'info') {
    state.v8.logs.unshift({ id: uid('v9log'), action: 'V9 · ' + action, details, jobId, level, time: `${todayLabel()} ${nowLabel()}` });
    state.v8.logs = state.v8.logs.slice(0, 450);
    if (state.v6?.audit) {
      state.v6.audit.unshift({ id: uid('audit'), action: 'V9 · ' + action, details, missionId: '', level, time: `${todayLabel()} ${nowLabel()}` });
      state.v6.audit = state.v6.audit.slice(0, 400);
    }
    save();
  }

  function slug(value) {
    return String(value || 'aihq-project').trim().replace(/[^a-zA-Z0-9._-]+/g, '-').replace(/^-+|-+$/g, '').slice(0, 70) || 'aihq-project';
  }

  function normalizeFile(file, fallbackName) {
    if (!file) return null;
    const path = String(file.path || file.name || fallbackName || 'file.txt').replace(/^\/+/, '').replace(/\\/g, '/');
    const content = typeof file.content === 'string' ? file.content : typeof file.text === 'string' ? file.text : typeof file.value === 'string' ? file.value : '';
    if (!path || path.includes('..')) return null;
    if (content.length > 250000) return null;
    return { path, content };
  }

  function collectProjectFiles(projectId, mission) {
    const found = [];
    const push = (file, name) => {
      const normalized = normalizeFile(file, name);
      if (normalized && !found.some(x => x.path === normalized.path)) found.push(normalized);
    };

    const candidates = [
      state.projectFiles?.[projectId],
      state.workspaces?.[projectId]?.files,
      state.workspace?.[projectId]?.files,
      state.files,
      state.studioFiles,
      project(projectId)?.files
    ];

    for (const source of candidates) {
      if (Array.isArray(source)) {
        source.filter(f => !f.projectId || f.projectId === projectId).forEach((f, i) => push(f, `workspace/file-${i + 1}.txt`));
      } else if (source && typeof source === 'object') {
        Object.entries(source).forEach(([name, value]) => {
          if (typeof value === 'string') push({ path: name, content: value }, name);
          else push(value, name);
        });
      }
    }

    if (!found.length) {
      const p = project(projectId);
      const lines = [
        `# ${p?.name || mission?.title || 'AI HQ Project'}`,
        '',
        `Generated by AI HQ V9 on ${todayLabel()} ${nowLabel()}.`,
        '',
        '## Mission',
        mission?.title || 'No mission title',
        '',
        '## Completed work'
      ];
      (mission?.tasks || []).forEach(t => {
        lines.push(`### ${t.title || t.role || 'Stage'}`);
        lines.push(String(t.result || t.output || t.summary || t.error || 'No text result'));
        lines.push('');
      });
      push({ path: 'AIHQ-PROJECT.md', content: lines.join('\n') });
    }

    return found.slice(0, 40);
  }

  function createProdJob(type, mission, payload, dependsOn = []) {
    const j = {
      id: uid('prodjob'),
      type,
      status: 'queued',
      projectId: mission.projectId,
      missionId: mission.id,
      payload,
      dependsOn,
      attempts: 0,
      progress: 0,
      result: null,
      error: '',
      artifacts: [],
      v9: true,
      created: `${todayLabel()} ${nowLabel()}`,
      updated: `${todayLabel()} ${nowLabel()}`
    };
    state.v8.jobs.push(j);
    return j;
  }

  function prepareProductionPipeline(missionId) {
    ensureV9();
    const mission = state.missions.find(m => m.id === missionId);
    if (!mission) return toast('Миссия не найдена');
    if (state.v8.jobs.some(j => j.v9 && j.missionId === missionId && !['failed','cancelled'].includes(j.status))) {
      return toast('Production pipeline уже создан');
    }

    const p = project(mission.projectId);
    const repoName = slug(p?.name || mission.title);
    const files = collectProjectFiles(mission.projectId, mission);
    const common = { repoName, projectName: p?.name || mission.title, ref: 'main' };

    const create = createProdJob('github.create_repo', mission, { ...common, private: false, description: p?.description || mission.title });
    const commit = createProdJob('github.commit', mission, { ...common, branch: 'main', files, fallbackContent: files[0]?.content || '' }, [create.id]);
    const test = createProdJob('test.run', mission, { ...common, suite: 'auto' }, [commit.id]);

    const type = String(p?.type || '').toLowerCase();
    let build;
    if (/android|apk/.test(type)) {
      build = createProdJob('apk.build', mission, { ...common, variant: 'debug' }, [test.id]);
    } else {
      build = createProdJob('vercel.deploy', mission, { ...common, environment: 'preview' }, [test.id]);
    }

    createProdJob('release.publish', mission, {
      ...common,
      name: `${p?.name || mission.title} — AI HQ release`,
      notes: 'Prepared by AI HQ V9 after tests and director approval.'
    }, [build.id]);

    v9Log('Production pipeline создан', `${mission.title} · ${files.length} файлов · repo ${repoName}`);
    addMemory('Production pipeline', `АРГО подготовил реальное выполнение миссии «${mission.title}»: GitHub → commit → tests → build/deploy → release.`, mission.projectId, 'АРГО');
    save(); render(); toast('Production pipeline готов');
  }

  function headers() {
    const h = { 'Content-Type': 'application/json' };
    if (token()) h.Authorization = 'Bearer ' + token();
    return h;
  }

  async function request(path, options = {}) {
    const base = baseUrl();
    if (!base) throw new Error('Укажите HTTPS-адрес Production Gateway');
    const r = await fetch(base + path, { ...options, headers: { ...headers(), ...(options.headers || {}) } });
    const raw = await r.text();
    let body = {};
    try { body = raw ? JSON.parse(raw) : {}; } catch { body = { text: raw }; }
    if (!r.ok) throw new Error(body.error || body.message || `HTTP ${r.status}`);
    return body;
  }

  async function checkProductionGateway() {
    try {
      const started = Date.now();
      const body = await request('/health', { method: 'GET' });
      state.v9.health = {
        ok: !!body.ok,
        version: body.version || '',
        service: body.service || '',
        providers: body.providers || {},
        latency: Date.now() - started,
        time: `${todayLabel()} ${nowLabel()}`
      };
      v9Log('Production Gateway доступен', `${state.v9.health.latency} ms · GitHub: ${body.providers?.github ? 'OK' : 'нет токена'} · Vercel: ${body.providers?.vercel ? 'OK' : 'нет токена'}`);
      save(); render(); toast('Production Gateway подключён');
    } catch (e) {
      state.v9.health = { ok: false, error: String(e.message || e), time: `${todayLabel()} ${nowLabel()}` };
      v9Log('Ошибка Production Gateway', state.v9.health.error, '', 'error');
      save(); render(); toast('Gateway недоступен');
    }
  }

  function depsReady(job) {
    return (job.dependsOn || []).every(id => state.v8.jobs.find(x => x.id === id)?.status === 'success');
  }

  function addArtifacts(job, list) {
    if (!Array.isArray(list)) return;
    for (const a of list) {
      if (!a) continue;
      const item = {
        id: uid('artifact'),
        jobId: job.id,
        projectId: job.projectId,
        name: a.name || 'artifact',
        url: a.url || '',
        artifactId: a.artifactId || '',
        created: `${todayLabel()} ${nowLabel()}`
      };
      if (!state.v8.artifacts.some(x => x.jobId === item.jobId && x.name === item.name && x.url === item.url)) state.v8.artifacts.unshift(item);
    }
  }

  function needsReleaseApproval(job) {
    if (job.type !== 'release.publish') return false;
    if (job.v9Approved) return false;
    if (!state.v9.approvals.some(a => a.jobId === job.id && a.status === 'pending')) {
      state.v9.approvals.unshift({
        id: uid('prodapproval'),
        jobId: job.id,
        status: 'pending',
        title: `Публикация ${project(job.projectId)?.name || 'проекта'}`,
        created: `${todayLabel()} ${nowLabel()}`
      });
      job.status = 'approval';
      v9Log('Требуется решение директора', 'Production release остановлен перед публикацией', job.id, 'warning');
      save();
    }
    return true;
  }

  function approveRelease(id) {
    const approval = state.v9.approvals.find(a => a.id === id);
    if (!approval) return;
    const job = state.v8.jobs.find(j => j.id === approval.jobId);
    if (!job) return;
    approval.status = 'approved';
    approval.decided = `${todayLabel()} ${nowLabel()}`;
    job.v9Approved = true;
    job.status = 'queued';
    v9Log('Директор одобрил release', project(job.projectId)?.name || '', job.id);
    save(); render(); toast('Release одобрен');
  }

  function rejectRelease(id) {
    const approval = state.v9.approvals.find(a => a.id === id);
    if (!approval) return;
    const job = state.v8.jobs.find(j => j.id === approval.jobId);
    if (!job) return;
    approval.status = 'rejected';
    approval.decided = `${todayLabel()} ${nowLabel()}`;
    job.status = 'cancelled';
    job.error = 'Публикация отклонена директором';
    v9Log('Release отклонён директором', project(job.projectId)?.name || '', job.id, 'warning');
    save(); render(); toast('Release отменён');
  }

  async function poll(job, remoteId) {
    for (let i = 0; i < Number(state.v9.settings.maxPolls || 90); i++) {
      await new Promise(r => setTimeout(r, Number(state.v9.settings.pollMs || 1200)));
      const body = await request('/jobs/' + encodeURIComponent(remoteId), { method: 'GET' });
      job.status = body.status || job.status;
      job.progress = Number(body.progress ?? job.progress ?? 0);
      job.result = body.result ?? job.result;
      job.error = body.error || '';
      addArtifacts(job, body.artifacts);
      job.updated = `${todayLabel()} ${nowLabel()}`;
      save(); render();
      if (['success','failed','cancelled'].includes(job.status)) return job.status === 'success';
    }
    job.status = 'failed';
    job.error = 'Production Gateway не завершил задание вовремя';
    return false;
  }

  async function runProductionJob(id) {
    ensureV9();
    const job = state.v8.jobs.find(j => j.id === id);
    if (!job) return false;
    if (!depsReady(job)) { toast('Сначала завершите предыдущие задания'); return false; }
    if (needsReleaseApproval(job)) { render(); toast('Нужно одобрение директора'); return false; }

    job.status = 'running';
    job.progress = 3;
    job.attempts = Number(job.attempts || 0) + 1;
    job.error = '';
    job.updated = `${todayLabel()} ${nowLabel()}`;
    v9Log('Production job запущен', job.type, job.id);
    save(); render();

    try {
      const body = await request('/jobs', {
        method: 'POST',
        body: JSON.stringify({
          clientJobId: job.id,
          type: job.type,
          projectId: job.projectId,
          missionId: job.missionId,
          payload: job.payload
        })
      });

      job.remoteId = body.id || '';
      job.status = body.status || 'success';
      job.progress = Number(body.progress ?? (job.status === 'success' ? 100 : 10));
      job.result = body.result || null;
      addArtifacts(job, body.artifacts);
      save(); render();

      let ok = job.status === 'success';
      if (!ok && job.remoteId && !['failed','cancelled'].includes(job.status)) ok = await poll(job, job.remoteId);

      if (ok) {
        job.status = 'success';
        job.progress = 100;
        v9Log('Production job завершён', job.type, job.id);
      } else if (job.status !== 'approval') {
        job.status = job.status === 'cancelled' ? 'cancelled' : 'failed';
        v9Log('Production job остановлен', `${job.type}: ${job.error || job.status}`, job.id, 'error');
      }
      save(); render();
      return ok;
    } catch (e) {
      job.status = 'failed';
      job.error = String(e.message || e);
      v9Log('Ошибка Production job', `${job.type}: ${job.error}`, job.id, 'error');
      save(); render();
      return false;
    }
  }

  async function runProductionPipeline(missionId = '') {
    ensureV9();
    for (let guard = 0; guard < 30; guard++) {
      const next = state.v8.jobs.find(j => j.v9 && (!missionId || j.missionId === missionId) && j.status === 'queued' && depsReady(j));
      if (!next) break;
      const ok = await runProductionJob(next.id);
      if (!ok) break;
    }
    save(); render();
  }

  function trialFiles() {
    return {
      'settings.gradle': `pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}
rootProject.name = 'AI-HQ-Trial-Notes'
include ':app'
`,
      'build.gradle': `plugins {
    id 'com.android.application' version '8.7.3' apply false
}
`,
      'gradle.properties': `org.gradle.jvmargs=-Xmx2g -Dfile.encoding=UTF-8
android.useAndroidX=false
`,
      'app/build.gradle': `plugins {
    id 'com.android.application'
}

android {
    namespace 'com.aihq.trialnotes'
    compileSdk 35

    defaultConfig {
        applicationId 'com.aihq.trialnotes'
        minSdk 23
        targetSdk 35
        versionCode 1
        versionName '1.0'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
`,
      'app/src/main/AndroidManifest.xml': `<manifest xmlns:android="http://schemas.android.com/apk/res/android">
    <application
        android:allowBackup="true"
        android:label="AI HQ Trial Notes"
        android:theme="@android:style/Theme.Material.Light.NoActionBar">
        <activity
            android:name=".MainActivity"
            android:exported="true">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
    </application>
</manifest>
`,
      'app/src/main/java/com/aihq/trialnotes/MainActivity.java': `package com.aihq.trialnotes;

import android.app.Activity;
import android.os.Bundle;
import android.content.SharedPreferences;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ArrayAdapter;
import android.widget.Button;
import android.widget.EditText;
import android.widget.LinearLayout;
import android.widget.ListView;
import android.widget.TextView;
import java.util.ArrayList;
import java.util.LinkedHashSet;
import java.util.Set;

public class MainActivity extends Activity {
    private final ArrayList<String> notes = new ArrayList<>();
    private ArrayAdapter<String> adapter;
    private SharedPreferences prefs;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        prefs = getSharedPreferences("notes", MODE_PRIVATE);
        notes.addAll(prefs.getStringSet("items", new LinkedHashSet<>()));

        LinearLayout root = new LinearLayout(this);
        root.setOrientation(LinearLayout.VERTICAL);
        root.setPadding(32, 32, 32, 32);

        TextView title = new TextView(this);
        title.setText("AI HQ Trial Notes");
        title.setTextSize(24f);
        root.addView(title, new LinearLayout.LayoutParams(
            ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.WRAP_CONTENT));

        EditText input = new EditText(this);
        input.setHint("Введите заметку");
        root.addView(input, new LinearLayout.LayoutParams(
            ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.WRAP_CONTENT));

        Button add = new Button(this);
        add.setText("Добавить");
        root.addView(add);

        ListView list = new ListView(this);
        adapter = new ArrayAdapter<>(this, android.R.layout.simple_list_item_1, notes);
        list.setAdapter(adapter);
        root.addView(list, new LinearLayout.LayoutParams(
            ViewGroup.LayoutParams.MATCH_PARENT, 0, 1f));

        add.setOnClickListener(v -> {
            String value = input.getText().toString().trim();
            if (!value.isEmpty()) {
                notes.add(value);
                input.setText("");
                save();
                adapter.notifyDataSetChanged();
            }
        });

        list.setOnItemLongClickListener((parent, view, position, id) -> {
            notes.remove(position);
            save();
            adapter.notifyDataSetChanged();
            return true;
        });

        setContentView(root);
    }

    private void save() {
        prefs.edit().putStringSet("items", new LinkedHashSet<>(notes)).apply();
    }
}
`,
      'README.md': `# AI HQ Trial Notes

Контрольный Android-проект для первого реального испытания AI HQ Production Gateway.

## Проверяемая цепочка
1. Gateway создаёт настоящий GitHub-репозиторий.
2. Gateway записывает эти файлы.
3. GitHub Actions запускает тестовый этап.
4. GitHub Actions собирает debug APK.
5. AI HQ получает ссылку на Actions/артефакт.

Долгое нажатие на заметку удаляет её.
`
    };
  }

  function createFirstRealTrial() {
    ensureV9();
    const old = state.projects.find(p => p.name === 'AI HQ Trial Notes');
    if (old) {
      const mission = state.missions.find(m => m.projectId === old.id);
      if (mission) {
        prepareProductionPipeline(mission.id);
        state.nav = 'production';
        save(); render();
        toast('Испытание уже подготовлено');
        return;
      }
    }

    const team = recommendTeam('Android');
    const p = normalizeProject({
      id: uid('p'),
      name: 'AI HQ Trial Notes',
      type: 'Android',
      status: 'Тестирование',
      progress: 70,
      priority: 'Высокий',
      description: 'Контрольный Android-проект для проверки реального Production Gateway: GitHub → Actions → APK.',
      team,
      tasks: 0,
      risks: [],
      workflow: [],
      artifacts: [],
      autopilot: {status:'idle', lastRun:''}
    });
    initWorkflow(p);
    state.projects.unshift(p);

    const files = trialFiles();
    Object.entries(files).forEach(([path,content]) => upsertFile(p.id, path, content, 'АРГО · Trial Mode'));

    const m = {
      id: uid('mission'),
      title: 'Первое реальное испытание AI HQ',
      goal: 'Проверить настоящий внешний контур: создать GitHub-репозиторий, записать Android-проект, запустить GitHub Actions и получить APK.',
      projectId: p.id,
      priority: 'Высокий',
      status: 'Готова к Production',
      engine: 'trial',
      pipeline: {status:'idle', lastRun:''},
      created: todayLabel(),
      tasks: [],
      messages: [],
      results: []
    };
    state.missions.unshift(m);
    planMission(m);
    addMemory('Первое реальное испытание', 'Подготовлен контрольный Android-проект AI HQ Trial Notes для проверки GitHub → Actions → APK.', p.id, 'АРГО');
    addEvent('Trial Mode подготовлен', 'AI HQ Trial Notes · реальный Production Gateway', '▶');
    save();

    prepareProductionPipeline(m.id);
    state.nav = 'production';
    save(); render();
    toast('Первое реальное испытание готово');
  }

  function productionPage() {
    ensureV9();
    const jobs = state.v8.jobs.filter(j => j.v9).slice().reverse();
    const approvals = state.v9.approvals.filter(a => a.status === 'pending');
    const h = state.v9.health;
    return `<section class="card v9-hero"><div><div class="director-title">AI HQ V${V9_VERSION}</div><h3>Production Gateway</h3><p class="meta">Реальный GitHub + Actions + Vercel через защищённый серверный контур</p></div><div class="hero-actions"><button class="btn primary" data-v9-trial>★ Первое реальное испытание</button><button class="btn" data-v9-run-all>▶ Выполнить production</button><button class="btn" data-v9-health>Проверить сервер</button></div></section>
    <div class="section-head"><h3>Сервер</h3><span>${h?.ok ? 'ONLINE' : 'OFFLINE'}</span></div>
    <section class="card v9-server"><label>Production Gateway URL<input id="v9Url" placeholder="https://your-gateway.vercel.app" value="${esc(state.v9.settings.gatewayUrl || '')}"></label><label>Короткоживущий session token<input id="v9Token" type="password" placeholder="Не сохраняется в приложении"></label><div class="v9-health ${h?.ok ? 'ok' : h ? 'bad' : ''}">${h?.ok ? `● ${esc(h.service || 'Gateway')} V${esc(h.version || '')} · ${h.latency} ms · GitHub ${h.providers?.github ? '✓' : '×'} · Vercel ${h.providers?.vercel ? '✓' : '×'}` : h ? `● ${esc(h.error || 'Ошибка')}` : '● Сервер ещё не проверен'}</div></section>
    ${approvals.length ? `<div class="section-head"><h3>Решения директора</h3><span>${approvals.length}</span></div><div class="v9-approvals">${approvals.map(a => { const j=state.v8.jobs.find(x=>x.id===a.jobId); return `<article class="card v9-approval"><div><b>${esc(a.title)}</b><div class="meta">release.publish · ${esc(project(j?.projectId)?.name || '')}</div></div><div class="v8-actions"><button class="btn primary mini" data-v9-approve="${a.id}">Одобрить релиз</button><button class="btn danger mini" data-v9-reject="${a.id}">Отклонить</button></div></article>`; }).join('')}</div>` : ''}
    <div class="section-head"><h3>Production jobs</h3><span>${jobs.length}</span></div>
    <div class="v9-jobs">${jobs.map(j => `<article class="card v9-job"><div class="row between"><div><b>${esc(j.type)}</b><div class="meta">${esc(project(j.projectId)?.name || '')}</div></div><span class="v8-status ${j.status}">${esc(j.status)}</span></div><div class="progress"><i style="width:${Math.max(0,Math.min(100,j.progress || 0))}%"></i></div>${j.error ? `<p class="v8-error">${esc(j.error)}</p>` : ''}<div class="row between"><span class="meta">Попыток: ${j.attempts || 0}</span><div class="v8-actions">${['queued','failed'].includes(j.status) ? `<button class="btn mini" data-v9-run="${j.id}">Запустить</button>` : ''}</div></div></article>`).join('') || '<div class="empty">Откройте миссию и создайте Production pipeline.</div>'}</div>
    <div class="section-head"><h3>Артефакты</h3><span>${state.v8.artifacts.length}</span></div>
    <div class="v8-artifacts">${state.v8.artifacts.slice(0,30).map(a => `<article class="card v8-artifact"><div><b>${esc(a.name)}</b><div class="meta">${esc(project(a.projectId)?.name || '')}</div></div>${a.url ? `<button class="btn mini" data-v9-open="${esc(a.url)}">Открыть</button>` : ''}</article>`).join('') || '<div class="empty">Артефактов пока нет.</div>'}</div>`;
  }

  const oldRenderPage = renderPage;
  renderPage = function() {
    if (state.nav === 'production') return productionPage();
    return oldRenderPage();
  };

  renderNav = function() {
    const nav = [
      ['office','⌂','Офис'],['projects','▤','Проекты'],['command','▦','Центр'],
      ['hierarchy','⌘','Структура'],['execute','▶','Исполнение'],['production','⬡','Production'],
      ['studio','◇','Студия'],['director','◆','Директор']
    ];
    return `<nav class="bottom-nav v9-nav">${nav.map(n => `<button class="nav-btn ${state.nav===n[0]?'active':''}" data-nav="${n[0]}"><strong>${n[1]}</strong>${n[2]}</button>`).join('')}</nav>`;
  };

  const oldDirectorPage = directorPage;
  directorPage = function() {
    return `<section class="card v9-director"><div><b>Production Gateway V9</b><p class="meta">Реальные репозитории, Actions, APK/деплой и релизы через серверные credentials.</p></div><button class="btn primary" data-navgo="production">Открыть Production</button></section>${oldDirectorPage().replace(/V8\.0/g,'V9.0')}`;
  };

  const oldOpenMission = openMission;
  openMission = function(id) {
    oldOpenMission(id);
    const actions = $('.hero-actions', $('#modal-root'));
    if (actions) {
      const create = document.createElement('button');
      create.className = 'btn primary';
      create.textContent = 'Production pipeline V9';
      create.onclick = () => prepareProductionPipeline(id);
      actions.appendChild(create);
      if (state.v8.jobs.some(j => j.v9 && j.missionId === id)) {
        const run = document.createElement('button');
        run.className = 'btn';
        run.textContent = 'Запустить production';
        run.onclick = () => runProductionPipeline(id);
        actions.appendChild(run);
      }
    }
  };

  const oldBindGlobal = bindGlobal;
  bindGlobal = function() {
    oldBindGlobal();
    $('[data-v9-trial]').forEach(b => b.onclick = createFirstRealTrial);
    $('[data-v9-run-all]').forEach(b => b.onclick = () => runProductionPipeline(''));
    $$('[data-v9-health]').forEach(b => b.onclick = checkProductionGateway);
    $$('[data-v9-run]').forEach(b => b.onclick = () => runProductionJob(b.dataset.v9Run));
    $$('[data-v9-approve]').forEach(b => b.onclick = () => approveRelease(b.dataset.v9Approve));
    $$('[data-v9-reject]').forEach(b => b.onclick = () => rejectRelease(b.dataset.v9Reject));
    $$('[data-v9-open]').forEach(b => b.onclick = () => { const url=b.dataset.v9Open; if (/^https?:\/\//i.test(url)) window.open(url,'_blank'); else toast(url); });
    const url = $('#v9Url');
    if (url) url.onchange = () => {
      state.v9.settings.gatewayUrl = url.value.trim();
      state.v8.settings = state.v8.settings || {};
      state.v8.settings.gatewayUrl = url.value.trim();
      save();
    };
    const tok = $('#v9Token');
    if (tok) { const syncToken = () => setToken(tok.value.trim()); tok.oninput = syncToken; tok.onchange = () => { syncToken(); toast(tok.value ? 'Session token принят' : 'Session token очищен'); }; }
  };

  ensureV9();
  v9Log('AI HQ V9.3 активирован', 'Исправлена привязка всех Production-кнопок');
  save();
  render();
})();